sudo: required
language: python
python:
 - 3.6

services:
 - docker
 - redis-server

install:
  - export env='dev'
  - cp core/eternity_default.yml core/eternity.yaml 
  - pip install -r dockerfiles/windless/requirements.txt
  - pip install -i http://pypi.douban.com/simple  -r requirements.txt --trusted-host pypi.douban.com
  - pip install -i http://pypi.douban.com/simple misaka cryptography --trusted-host pypi.douban.com
  - cd core && python melody.py

script:
  - curl 0.0.0.0:8080
