redis:
    image: redis
    volumes:
        - /home/chiaki/iventory/data:/data
    ports:
        - "127.0.0.1:6379:6379"

windless:
    image: windless/server:v1
    volumes:
        - /srv/www:/code
    links:
        - redis:redis
    ports:
        - "127.0.0.1:1064:1064"
    command: bash /code/dockerfiles/run.sh